/**
 * Build dsh-context-lens into `lib/`.
 *
 * The package deliberately carries no build-time dependency: the official
 * `clientBundle()` preset lives inside the harness monorepo and is not
 * published (docs/cookbook/adding-a-settings-card.md states a package outside
 * the repository "has to reproduce the same output format itself"). So this
 * script is a small, dependency-free assembler for that exact format.
 *
 * Two artifacts come out:
 *
 *   lib/index.js  — the host half, plain Node ESM. `src/host/` is copied to
 *                   `lib/host/` and `lib/index.js` re-exports it, so the
 *                   published entry point matches `exports["."]`.
 *   lib/client.js — the browser half, a lazy-CJS closure factory:
 *                   `window.__ModuleLoader__.load({ id, factory })` whose
 *                   factory returns the cordis plugin exports.
 *
 * Client source is authored as plain CommonJS under `src/client/`, which is
 * exactly the format the loader materializes, so wrapping is mechanical: each
 * file becomes one registry entry and relative `require()` calls resolve
 * inside the bundle while bare specifiers fall through to the injected
 * `require` (the shell's frozen baseline module table).
 */

import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'src')
const LIB = join(root, 'lib')

/** The browser module identity; must equal the package name (loader row id). */
const PACKAGE_NAME = 'dsh-context-lens'

/** Recursively list every file under `dir`, as POSIX-style paths relative to it. */
async function listFiles(dir, base = dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await listFiles(full, base))
    else if (entry.isFile()) out.push(relative(base, full).split(sep).join('/'))
  }
  return out.sort()
}

/**
 * Wrap one client module as a factory-body entry.
 * @param source - the module's CommonJS source text.
 * @returns the registry-entry source.
 */
function wrapModule(source) {
  return `function (require, module, exports) {\n${source}\n}`
}

/**
 * Emit the lazy-CJS bundle. Import order is irrelevant: every entry is a
 * function body executed on demand by the internal registry.
 * @param modules - module key to wrapped source.
 * @param entry - the entry module key.
 * @returns the complete bundle text.
 */
function emitBundle(modules, entry) {
  const registry = Object.entries(modules)
    .map(([key, body]) => `\t\t${JSON.stringify(key)}: ${body},`)
    .join('\n')

  return `/**
 * dsh-context-lens — browser half.
 *
 * Generated by scripts/build.mjs from src/client/. Do not edit by hand.
 *
 * Lazy-CJS closure factory: running this bundle only registers the factory;
 * module bodies (including the style injection) execute at materialization.
 * Bare requires resolve against the shell's frozen baseline module table.
 */
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(PACKAGE_NAME)},
\tfactory: (require) => {
\t\tvar module = { exports: {} }
\t\tvar exports = module.exports
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" })

\t\t// Bundled modules, keyed by their source path relative to src/client/.
\t\tvar __defs = {
${registry}
\t\t}

\t\tvar __cache = Object.create(null)

\t\t/** Normalize a POSIX-ish path, resolving "." and ".." segments. */
\t\tfunction __normalize(path) {
\t\t\tvar parts = path.split("/")
\t\t\tvar out = []
\t\t\tfor (var i = 0; i < parts.length; i++) {
\t\t\t\tvar part = parts[i]
\t\t\t\tif (part === "" || part === ".") continue
\t\t\t\tif (part === "..") { out.pop(); continue }
\t\t\t\tout.push(part)
\t\t\t}
\t\t\treturn out.join("/")
\t\t}

\t\t/** Resolve a relative specifier against the requiring module's directory. */
\t\tfunction __resolve(spec, fromKey) {
\t\t\tvar dir = fromKey.indexOf("/") === -1 ? "" : fromKey.slice(0, fromKey.lastIndexOf("/"))
\t\t\tvar joined = __normalize(dir === "" ? spec : dir + "/" + spec)
\t\t\tvar candidates = [joined, joined + ".cjs", joined + ".js", joined + "/index.cjs", joined + "/index.js"]
\t\t\tfor (var i = 0; i < candidates.length; i++) {
\t\t\t\tif (Object.prototype.hasOwnProperty.call(__defs, candidates[i])) return candidates[i]
\t\t\t}
\t\t\tthrow new Error("[context-lens] unresolved internal module " + JSON.stringify(spec) + " from " + fromKey)
\t\t}

\t\t/** Materialize one bundled module; bare specifiers go to the shell table. */
\t\tfunction __load(key) {
\t\t\tif (__cache[key] !== undefined) return __cache[key].exports
\t\t\tvar definition = __defs[key]
\t\t\tif (definition === undefined) throw new Error("[context-lens] unknown module " + JSON.stringify(key))
\t\t\tvar record = { exports: {} }
\t\t\t__cache[key] = record
\t\t\tdefinition(function (spec) {
\t\t\t\treturn spec.charAt(0) === "." ? __load(__resolve(spec, key)) : require(spec)
\t\t\t}, record, record.exports)
\t\t\treturn record.exports
\t\t}

\t\treturn __load(${JSON.stringify(entry)})
\t}
})
`
}

/** Copy the host half and write the published entry point. */
async function buildHost() {
  const from = join(SRC, 'host')
  const to = join(LIB, 'host')
  await cp(from, to, { recursive: true })
  // The exported entry re-exports the copied host tree, so relative imports
  // inside lib/host keep working and `exports["."]` stays a single file.
  await writeFile(join(LIB, 'index.js'), "export * from './host/index.js'\n")
  return (await listFiles(from)).map(file => `host/${file}`)
}

/** Bundle the browser half. */
async function buildClient() {
  const base = join(SRC, 'client')
  const files = (await listFiles(base)).filter(file => file.endsWith('.cjs'))
  const modules = {}
  for (const file of files) {
    modules[file] = wrapModule(await readFile(join(base, file), 'utf8'))
  }
  const entry = 'index.cjs'
  if (!(entry in modules)) throw new Error(`client entry ${entry} is missing from ${base}`)
  await writeFile(join(LIB, 'client.js'), emitBundle(modules, entry))
  return files
}

async function main() {
  await rm(LIB, { recursive: true, force: true })
  await mkdir(LIB, { recursive: true })
  const host = await buildHost()
  const client = await buildClient()
  process.stdout.write(`built lib/index.js (host: ${host.length} modules)\n`)
  process.stdout.write(`built lib/client.js (client: ${client.length} modules)\n`)
}

await main()
